name: Python Tests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # Ou la version que tu utilises

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      env:
        PR_TITLE: ${{ github.event.pull_request.title }}
      run: |
        echo "Titre PR : $PR_TITLE"
        python regex_verif.py ${{github.event.pull_request.title}}
