# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Elixir CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build-credo:

    name: Mix credo
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - uses: owner/repo@.github/actions/setup-elixir
    - name: Run credo
      run: mix credo

  build-test:

    name: Mix test
    runs-on: ubuntu-22.04
    if: always()

    steps:
      - uses: actions/checkout@v4
      - uses: owner/repo@.github/actions/setup-elixir
      - name: Run test
        run: mix test

  test:
    name: Regex verif
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # Ou la version que tu utilises

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run tests
      env:
        PR_TITLE: ${{ github.event.pull_request.title }}
      run: |
        python .github/workflows/regex_verif.py "$PR_TITLE"
